name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Configurar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar Node.js (por ejemplo, si usas un proyecto Node.js)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: npm install

      # Paso 4: Ejecutar pruebas (si tienes un script de pruebas en package.json)
      - name: Run tests
        run: npm test

      # Paso 5: Construir el proyecto (si aplica)
      - name: Build project
        run: npm run build
